package Jasenrekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Jasenrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.29 21:28:12 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HarjoitusTest {



  // Generated by ComTest BEGIN
  /** test_rekisteroi */
  @Test
  public void test_rekisteroi() {    // Harjoitus: 13
    Harjoitus harjoitus1 = new Harjoitus(); 
    assertEquals("From: Harjoitus line: 16", 0, harjoitus1.getTunnusNro()); 
    harjoitus1.rekisteroi(); 
    Harjoitus harjoitus2 = new Harjoitus(); 
    harjoitus2.rekisteroi(); 
    int n1 = harjoitus1.getTunnusNro(); 
    int n2 = harjoitus2.getTunnusNro(); 
    assertEquals("From: Harjoitus line: 22", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** test_parse */
  @Test
  public void test_parse() {    // Harjoitus: 26
    Harjoitus harjoitus = new Harjoitus(); 
    harjoitus.parse("5|20200324|1600|1730|1|-1|Hyvin porukkaa paikalla|"); 
    assertEquals("From: Harjoitus line: 30", 5, harjoitus.getTunnusNro()); 
    assertEquals("From: Harjoitus line: 31", true, harjoitus.toString().startsWith("5|20200324|1600|1730")); 
    harjoitus.rekisteroi(); 
    int n = harjoitus.getTunnusNro(); 
    harjoitus.rekisteroi(); 
    assertEquals("From: Harjoitus line: 36", n+1, harjoitus.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** test_equals */
  @Test
  public void test_equals() {    // Harjoitus: 40
    Harjoitus harjoitus1 = new Harjoitus(); 
    harjoitus1.parse("0|20200324|1600|1730|1|-1|Hyvin porukkaa paikalla|"); 
    Harjoitus harjoitus2 = new Harjoitus(); 
    harjoitus2.parse("0|20200324|1600|1730|1|-1|Hyvin porukkaa paikalla|"); 
    Harjoitus harjoitus3 = new Harjoitus(); 
    harjoitus3.parse("2|20191215|1500|1700|2|4|Hyva treeni"); 
    assertEquals("From: Harjoitus line: 49", true, harjoitus1.toString().equals(harjoitus2.toString())); 
    assertEquals("From: Harjoitus line: 50", true, harjoitus2.toString().equals(harjoitus1.toString())); 
    assertEquals("From: Harjoitus line: 51", false, harjoitus1.toString().equals(harjoitus3.toString())); 
    assertEquals("From: Harjoitus line: 52", false, harjoitus3.toString().equals(harjoitus2.toString())); 
    assertEquals("From: Harjoitus line: 53", false, harjoitus3.toString().equals(null)); 
  } // Generated by ComTest END
}