package Jasenrekisteri.test;
// Generated by ComTest BEGIN
import java.io.File;
import java.util.List;
import static org.junit.Assert.*;
import org.junit.*;
import Jasenrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.05.06 18:45:41 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HarjoituksetTest {



  // Generated by ComTest BEGIN
  /** test_lisaa_poista */
  @Test
  public void test_lisaa_poista() {    // Harjoitukset: 22
    Harjoitukset harjotukset = new Harjoitukset(); 
    Harjoitus harj1 = new Harjoitus(); harj1.parse("1|20191215|1500|1700|2|4|Hyva treeni"); 
    Harjoitus harj2 = new Harjoitus(); harj2.parse("2|20191220|1800|2000|5|1|Hyva treeni"); 
    Harjoitus harj3 = new Harjoitus(); harj3.parse("3|20191011|1600|1900|1|2|Hyva treeni"); 
    Harjoitus harj4 = new Harjoitus(); harj4.parse("4|20190907|1700|1830|3|4|Hyva treeni"); 
    Harjoitus harj5 = new Harjoitus(); harj5.parse("5|20180316|1800|1930|5|4|Hyva treeni"); 
    harjotukset.lisaa(harj1); 
    harjotukset.lisaa(harj2); 
    harjotukset.lisaa(harj3); 
    harjotukset.lisaa(harj4); 
    List<Harjoitus> h = harjotukset.annaHarjoitukset(3); 
    assertEquals("From: Harjoitukset line: 38", 1, h.size()); 
    assertEquals("From: Harjoitukset line: 39", harj3, h.get(0)); 
  } // Generated by ComTest END
}