package Jasenrekisteri.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import Jasenrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.05.06 16:38:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JasenetTest {



  // Generated by ComTest BEGIN
  /** 
   * test_lisaa_poista 
   * @throws SailoException when error
   */
  @Test
  public void test_lisaa_poista() throws SailoException {    // Jasenet: 15
    Jasenet jasenet = new Jasenet(); 
    Jasen jasen1 = new Jasen(); jasen1.parse("1|Marko Esimerkki|1999|1|0320324789|23|7|0.0|2500|Tosi rehti"); 
    Jasen jasen2 = new Jasen(); jasen2.parse("2|Marko Esimerkki|2002|1|0923423789|30|0|0.0|2200|Juu"); 
    Jasen jasen3 = new Jasen(); jasen3.parse("5|Marko Esimerkki|1990|1|0825464489|15|15|0.0|2700|Ala laita tallasta"); 
    Jasen jasen4 = new Jasen(); jasen4.parse("3|Marko Esimerkki|1994|1|0522243789|13|17|0.0|2800|Lisatietoja"); 
    Jasen jasen5 = new Jasen(); jasen5.parse("4|Marko Esimerkki|1997|1|0328768789|10|20|0.0|2100|Hyvat kengat"); 
    jasenet.lisaa(jasen1); 
    jasenet.lisaa(jasen2); 
    jasenet.lisaa(jasen3); 
    jasenet.lisaa(jasen4); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * test_tiedosto 
   * @throws SailoException when error
   */
  @Test
  public void test_tiedosto() throws SailoException {    // Jasenet: 34
    Jasenet jasenet = new Jasenet(); 
    Jasen jasen1 = new Jasen(); jasen1.parse("1|Marko Esimerkki|1999|1|0320324789|23|7|0.0|2500|Tosi rehti"); 
    Jasen jasen2 = new Jasen(); jasen2.parse("2|Marko Esimerkki|2002|1|0923423789|30|0|0.0|2200|Juu"); 
    Jasen jasen3 = new Jasen(); jasen3.parse("5|Marko Esimerkki|1990|1|0825464489|15|15|0.0|2700|Ala laita tallasta"); 
    Jasen jasen4 = new Jasen(); jasen4.parse("3|Marko Esimerkki|1994|1|0522243789|13|17|0.0|2800|Lisatietoja"); 
    Jasen jasen5 = new Jasen(); jasen5.parse("4|Marko Esimerkki|1997|1|0328768789|10|20|0.0|2100|Hyvat kengat"); 
    String tiedNimi = "testiJoukkue"; 
    File ftied = new File(tiedNimi+".dat"); 
    jasenet.lueTiedostosta(tiedNimi); 
    jasenet.lisaa(jasen1); 
    jasenet.lisaa(jasen2); 
    jasenet.lisaa(jasen3); 
    jasenet.lisaa(jasen4); 
    jasenet.lisaa(jasen5); 
    jasenet.tallenna(); 
    jasenet = new Jasenet(); 
    jasenet.lueTiedostosta(tiedNimi); 
    Jasen i[] = new Jasen[5]; 
    i[0] = jasen1; 
    i[1] = jasen2; 
    i[2] = jasen3; 
    i[3] = jasen4; 
    i[4] = jasen5; 
    assertEquals("From: Jasenet line: 60", jasen1.toString(), i[0].toString()); 
    assertEquals("From: Jasenet line: 61", jasen2.toString(), i[1].toString()); 
    assertEquals("From: Jasenet line: 62", jasen3.toString(), i[2].toString()); 
    assertEquals("From: Jasenet line: 63", jasen4.toString(), i[3].toString()); 
    assertEquals("From: Jasenet line: 64", jasen5.toString(), i[4].toString()); 
    try {
    i[5].toString(); 
    fail("Jasenet: 65 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    jasenet.tallenna(); 
    ftied.delete(); 
  } // Generated by ComTest END
}